# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  #push:
    #branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    #- name: Run Program
      #run: java -jar target/*.jar &
    
    #- name: Sleep command
      #run: sleep 90
    
    #- name: Test endpoint
     # run: curl localhost:8080
    
    #- name: Run Unit Test
      #run: mvn -B test
    
    #- name: Upload artifact
      #uses: actions/upload-artifact@v1.0.0
      #with:
        #name: spring-petclinic
        #path: target/surefire-reports
        
    - name: Build the Docker image (the dot means build the image in the current directory)
      run: docker build . --file Dockerfile --tag petclinic:latest 
      
    - name: Run Docker
     # run: docker run -dv maven:latest
      run: docker run -p 8000:8080 -t --name petclinic petclinic:latest
      
    - name: Copy artifact from docker image
      run: docker cp petclinic:/app/target/surefire-reports .
      
    - name: Upload/Save artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: spring-petclinic-artifact
        path: surefire-reports
      
        
        
        
        
        
        
        
        
        
        
